server:
  port: 8100

spring:
  application:
    name: currency-calculation-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true