server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: calculation-service
          uri: lb://CURRENCY-CALCULATION-SERVICE/
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}